[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
loan = "5RWvthGiq4HQbATBQypgM81J4ioQg37UwPqyigjP7vJZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
